export const copy = {
  en: {
    languageLabel: 'العربية',
    brandTagline: 'learning, made legible',
    nav: {
      path: 'The path',
      lesson: 'Try the moment',
      trust: 'Trust, built in',
    },
    heroEyebrow: 'Edu-Canvas · from intent to insight',
    heroTitleStart: 'From a teacher’s idea to',
    heroTitleAccent: 'a student’s',
    heroTitleEnd: 'aha.',
    heroDescription:
      'Turn a teacher’s plain-language idea into a safe, reviewed lesson — then give a learner one clear next step that makes the relationship click.',
    heroPrimary: 'Try the student moment',
    heroSecondary: 'See how it moves',
    heroMeta: ['Teacher-led', 'Grades 3–6', 'English · العربية'],
    stageLabel: 'The moment made visible',
    stageDescription: 'Different names. One portion of a whole.',
    stageSource: 'one-half',
    stageTarget: 'same portion',
    stageDistractor: 'not the same portion',
    lessonKicker: 'The student moment',
    lessonTitle: 'Now let the learner find the connection.',
    lessonDescription:
      'The source is clear. Choose every name that still means one-half, then reveal why they belong together. This is a practice moment — no score, no pressure.',
    lessonInstruction: 'Which names still mean one-half?',
    lessonSourceLabel: 'Source',
    lessonSourceFraction: '1/2',
    lessonSourceWords: 'one-half',
    lessonTargetLabel: 'Find the same portion',
    lessonHint: 'A hint: imagine each fraction as part of a shaded whole.',
    lessonHintAction: 'Open hint',
    lessonRevealAction: 'Show the connection',
    lessonResetAction: 'Start again',
    lessonEmptyStatus: 'Choose at least one name to begin.',
    lessonSelectedStatus: 'selected — keep looking for the same portion.',
    lessonRevealedStatus:
      'There it is: the names change, but the portion stays the same.',
    lessonRevealTitle: 'Same portion. Different names.',
    lessonRevealDescription:
      'Two fourths, three sixths, and four eighths each cover the same half. That connection makes the next step explainable.',
    lessonPreviewNote: 'A practice moment — no score, no pressure.',
    journeyKicker: 'The path',
    journeyTitle:
      'The teacher stays in the loop. The student gets the next clear step.',
    journeyDescription:
      'Edu-Canvas carries the draft and the checks. People keep the judgment, and the learner gets an activity that explains itself.',
    phases: [
      {
        id: 'shape' as const,
        number: '01',
        label: 'Teacher starts with intent',
        title: 'A plain-language idea becomes a lesson draft.',
        body: 'A teacher begins in English or Arabic, with the idea already in their head. The system turns that intent into a small set of focused, standards-aligned possibilities.',
        note: 'Start from the idea, not a form',
      },
      {
        id: 'review' as const,
        number: '02',
        label: 'Teacher reviews the handoff',
        title: 'The draft is checked before it travels.',
        body: 'The lesson is validated, made accessible, and placed in the teacher’s hands for review. Nothing reaches a learner until a person says it is right for the class.',
        note: 'No unreviewed activity reaches a learner',
      },
      {
        id: 'match' as const,
        number: '03',
        label: 'Student sees the idea',
        title: 'One focused choice makes the relationship visible.',
        body: 'The learner starts from the source, chooses the names that belong together, and gets immediate feedback that explains why the connection works.',
        note: 'Semantic, keyboard-ready, touch-friendly',
      },
      {
        id: 'adapt' as const,
        number: '04',
        label: 'The next step earns its place',
        title: 'The next activity has a reason.',
        body: 'After the attempt, a clear learning signal points toward the next approved activity — forward when the idea is ready, back to a prerequisite when it is not.',
        note: 'Explainable, reversible, teacher-visible',
      },
    ],
    roleKicker: 'The human boundary',
    roleTitle: 'The system carries the busywork. People keep the judgment.',
    roleDescription:
      'Edu-Canvas is designed around a simple division of labor: people decide what matters; the system makes the route through it clearer.',
    teacherTab: 'For teachers',
    studentTab: 'For students',
    teacherQuote:
      '“I can start with the way I already think about the lesson, then spend my time on the choice that matters: is this right for my class?”',
    teacherPoint: 'A reviewable pack, not a black-box publish button.',
    studentQuote:
      '“I know what to do next — and when I get it, I can see why the names belong together.”',
    studentPoint:
      'One focused activity, with a next step that earns its place.',
    trustKicker: 'Trust, built in',
    trustTitle: 'The learning loop stays clear, private, and reviewable.',
    trustItems: [
      [
        'Teacher approval',
        'Every generated variant is reviewed before a learner sees it.',
      ],
      [
        'Private by design',
        'The learner gets the explanation without exposing the answer or mastery decision.',
      ],
      [
        'Safe by default',
        'The demo uses synthetic fixtures; real student data waits for the right approvals.',
      ],
    ],
    footerLine: 'A calm interface for the hard work of learning.',
    footerAction: 'Try the student moment',
    themeToDark: 'Use dark theme',
    themeToLight: 'Use light theme',
  },
  ar: {
    languageLabel: 'English',
    brandTagline: 'التعلّم بوضوح',
    nav: {
      path: 'المسار',
      lesson: 'جرّب اللحظة',
      trust: 'الثقة أولاً',
    },
    heroEyebrow: 'Edu-Canvas · من الفكرة إلى الفهم',
    heroTitleStart: 'من فكرة المعلّم إلى',
    heroTitleAccent: 'لحظة فهم',
    heroTitleEnd: 'المتعلّم.',
    heroDescription:
      'حوّل فكرة المعلّم كما يعبّر عنها بلغته الطبيعية إلى درس آمن وقابل للمراجعة، ثم امنح المتعلّم خطوة واضحة تجعل العلاقة مفهومة.',
    heroPrimary: 'جرّب لحظة المتعلّم',
    heroSecondary: 'شاهد كيف يتحرّك',
    heroMeta: ['بقيادة المعلّم', 'الصفوف 3–6', 'العربية · English'],
    stageLabel: 'لحظة الفهم مرئية',
    stageDescription: 'أسماء مختلفة. جزء واحد من الكل.',
    stageSource: 'النصف',
    stageTarget: 'الجزء نفسه',
    stageDistractor: 'جزء مختلف',
    lessonKicker: 'لحظة المتعلّم',
    lessonTitle: 'الآن دع المتعلّم يكتشف العلاقة.',
    lessonDescription:
      'المصدر واضح. اختر كل اسم يعني النصف نفسه، ثم أظهر لماذا تنتمي هذه الأسماء معاً. هذه لحظة تدريب — بلا درجات ولا ضغط.',
    lessonInstruction: 'أيّ الأسماء تعني النصف؟',
    lessonSourceLabel: 'المصدر',
    lessonSourceFraction: '1/2',
    lessonSourceWords: 'النصف',
    lessonTargetLabel: 'ابحث عن الجزء نفسه',
    lessonHint: 'تلميح: تخيّل كل كسر جزءاً مظلّلاً من شكل كامل.',
    lessonHintAction: 'افتح التلميح',
    lessonRevealAction: 'أظهر العلاقة',
    lessonResetAction: 'ابدأ من جديد',
    lessonEmptyStatus: 'اختر اسماً واحداً على الأقل للبدء.',
    lessonSelectedStatus: 'تم الاختيار — واصل البحث عن الجزء نفسه.',
    lessonRevealedStatus: 'ها هي العلاقة: تتغيّر الأسماء، لكن الجزء يبقى نفسه.',
    lessonRevealTitle: 'جزء واحد. أسماء مختلفة.',
    lessonRevealDescription:
      'جزآن من أربعة، وثلاثة أجزاء من ستة، وأربعة أجزاء من ثمانية تمثّل النصف نفسه. وهكذا تصبح الخطوة التالية قابلة للتفسير.',
    lessonPreviewNote: 'لحظة تدريب — بلا درجات ولا ضغط.',
    journeyKicker: 'المسار',
    journeyTitle:
      'يبقى المعلّم داخل الحلقة، ويحصل المتعلّم على الخطوة الواضحة التالية.',
    journeyDescription:
      'يتولى Edu-Canvas المسودة والفحوصات. ويحتفظ البشر بالقرار، ويحصل المتعلّم على نشاط يشرح نفسه.',
    phases: [
      {
        id: 'shape' as const,
        number: '01',
        label: 'يبدأ المعلّم بفكرته',
        title: 'تتحوّل الفكرة المعبّر عنها طبيعياً إلى مسودة درس.',
        body: 'يبدأ المعلّم بالعربية أو بالإنجليزية، وبالفكرة التي يعرفها مسبقاً. يحوّل النظام هذه النية إلى مجموعة صغيرة من الاحتمالات المركّزة والمتوافقة مع المعايير.',
        note: 'ابدأ من الفكرة، لا من نموذج طويل',
      },
      {
        id: 'review' as const,
        number: '02',
        label: 'يراجع المعلّم التسليم',
        title: 'تُفحص المسودة قبل أن تنتقل.',
        body: 'تُراجع المسودة وتُجعل ملائمة للجميع، ثم تعود إلى المعلّم. لا يصل أي شيء إلى المتعلّم حتى يقرّر شخص أنها مناسبة لصفّه.',
        note: 'لا يصل نشاط غير معتمد إلى المتعلّم',
      },
      {
        id: 'match' as const,
        number: '03',
        label: 'يرى المتعلّم الفكرة',
        title: 'اختيار واحد مركّز يجعل العلاقة مرئية.',
        body: 'يبدأ المتعلّم بالمصدر، ويختار الأسماء التي تنتمي إليه، ثم يحصل على استجابة فورية تشرح لماذا تنجح العلاقة.',
        note: 'دلالي، ملائم للوحة المفاتيح، مناسب للمس',
      },
      {
        id: 'adapt' as const,
        number: '04',
        label: 'تستحق الخطوة التالية مكانها',
        title: 'للنشاط التالي سبب واضح.',
        body: 'بعد المحاولة، تشير إشارة تعلم واضحة إلى النشاط المعتمد التالي — إلى الأمام عندما تكون الفكرة جاهزة، أو إلى متطلب سابق عندما لا تكون كذلك.',
        note: 'قابل للتفسير، قابل للتراجع، ظاهر للمعلّم',
      },
    ],
    roleKicker: 'الحدّ الإنساني',
    roleTitle: 'يتولى النظام الأعمال المتكررة. ويحتفظ البشر بالقرار.',
    roleDescription:
      'بُني Edu-Canvas على تقسيم بسيط للعمل: يقرر البشر ما المهم، ويجعل النظام الطريق إليه أوضح.',
    teacherTab: 'للمعلّمين',
    studentTab: 'للمتعلّمين',
    teacherQuote:
      '«أبدأ بالطريقة التي أفكر بها في الدرس، ثم أركّز وقتي على القرار المهم: هل هذا مناسب لصفّي؟»',
    teacherPoint: 'حزمة قابلة للمراجعة، لا زر نشر غامض.',
    studentQuote:
      '«أعرف ما الذي أفعله بعد ذلك — وعندما أجيب بشكل صحيح، أرى لماذا تنتمي الكسور معاً.»',
    studentPoint: 'نشاط واحد مركز، وخطوة تالية تستحق مكانها.',
    trustKicker: 'الثقة أولاً',
    trustTitle: 'تبقى حلقة التعلّم واضحة وخاصة وقابلة للمراجعة.',
    trustItems: [
      ['اعتماد المعلّم', 'تُراجع كل صيغة مولّدة قبل أن يراها المتعلّم.'],
      [
        'الخصوصية أولاً',
        'يحصل المتعلّم على التفسير دون كشف الإجابة أو قرار الإتقان.',
      ],
      [
        'آمن افتراضياً',
        'تستخدم المعاينة بيانات اصطناعية؛ وتنتظر بيانات المتعلمين الحقيقية الموافقات المناسبة.',
      ],
    ],
    footerLine: 'واجهة هادئة للعمل الصعب الذي يتطلبه التعلّم.',
    footerAction: 'جرّب لحظة المتعلّم',
    themeToDark: 'استخدم المظهر الداكن',
    themeToLight: 'استخدم المظهر الفاتح',
  },
} as const

export type LandingCopy = (typeof copy)[keyof typeof copy]
